---
- hosts: all
  remote_user: root
  vars:
  tasks:
  - name:  copy daemons file in /etc/quagga 
    sudo:  yes
    template:  src=quagga.daemons_file dest=/etc/quagga/daemons

  - name:  copy Switch-Leaf-1a Quagga.conf
    sudo:  yes
    copy:  src=Switch-Leaf-1a-Quagga.conf dest=/etc/quagga/Quagga.conf
    when:  inventory_hostname == "Switch-Leaf-1a"

  - name:  copy Switch-Leaf-1a Quagga.conf
    sudo:  yes
    copy:  src=Switch-Leaf-1a-interfaces dest=/etc/network/interfaces
    when:  inventory_hostname == "Switch-Leaf-1a"

  - name:  copy Switch-Leaf-1b Quagga.conf
    sudo:  yes
    copy:  src=Switch-Leaf-1b-Quagga.conf dest=/etc/quagga/Quagga.conf
    when:  inventory_hostname == "Switch-Leaf-1b"

  - name:  copy Switch-Leaf-1b Quagga.conf
    sudo:  yes
    copy:  src=Switch-Leaf-1b-interfaces dest=/etc/network/interfaces
    when:  inventory_hostname == "Switch-Leaf-1b"

  - name:  restart Quagga
    sudo:  yes
    service:  name=quagga state=restarted

  - name:  Reload interfaces file
    sudo:  yes
    command: /sbin/ifreload -a 
